### ISSUE TITLE
FR: frontmatter/yaml

### ISSUE THREAD

**Issue by menagerie198** [bkis/obsidian-hard-breaks#1]
Would it be possible to exclude frontmatter/yaml from the plugin? Currently, adding two spaces to the frontmatter delimiter (`---`) turns the frontmatter/yaml block into regular text. Quite a problem for me as I use that metadata in Dataview, and for filtering searches. Cheers

**Comment by bkis** [comment]
Oh, that's a problem indeed. Thank you for creating an issue! I'll look into it as soon as I find the time.

Right now, the plugin runs on every change of the editor. So its operation must not be too resource intensive. I thought about only running the auto hard breaks functionality each time a document is saved. That would be enough and would allow to parse the document for front matter, code blocks, etc...

**Comment by bkis** [comment]
After a lot of tinkering, I dropped the "Automatic hard breaks" feature for [reasons explained here](https://github.com/bkis/obsidian-hard-breaks#automatic-hard-breaks-while-writing). For now. The plugin offers only the editor command to make all line breaks hard breaks at this point. Maybe I'll find another way to automate the command in the future (If Obsidian introduces an event on switching documents or something).

The good news is: It now parses the markdown to detect code blocks, front matter, etc. and only ever touches paragraphs of text! I consider this issue resolved for now. Thanks again for the feedback!
